#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/wg0.conf

if [[ -f "$CONFIG_FILE" ]]; then
  # comment DNS sections from wg0.conf
  sed -i 's/^[^#]*DNS/#&/' "$CONFIG_FILE"
  # comment Pre/Post hooks from wg0.conf
  # sed -i -E 's/^[^#]*(Pre|Post)(Up|Down)/#&/' "$CONFIG_FILE"
  # fix permission warning
  chmod 600 "$CONFIG_FILE"
fi

# patch to net.ipv4.conf.all.src_valid_mark
# source: https://lists.zx2c4.com/pipermail/wireguard/2023-February/007936.html
if [[ $(sysctl -n net.ipv4.conf.all.src_valid_mark) == 1 ]]; then
  # comment the line if already set
  sed -i '/cmd sysctl -q net.ipv4.conf.all.src_valid_mark=1/s/^/#/' /usr/bin/wg-quick
fi

# export useful variables
dockernet=$(ip route show default)
export BR_DEV=$(echo $dockernet | awk '{print $5}')
export BR_GATEWAY=$(echo $dockernet | awk '{print $3}')
export BR_CIDR=$(ip -o addr show $BR_DEV | awk '{print $4}')

# start wireguard
exec wg-quick up "$CONFIG_FILE"
