#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/qBittorrent/config/qBittorrent.conf

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="/tmp/$0.$$.$RANDOM"
  cat <<EOF >"$TMP_FILE"
[BitTorrent]
Session\Interface=wg0

[Preferences]
WebUI\HostHeaderValidation=false
WebUI\UseUPnP=false
WebUI\LocalHostAuth=false
EOF

  install -dm755 -o $PUID -g $PGID \
    /config/qBittorrent \
    /config/qBittorrent/config
  install -m644  -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
elif [[ $(grep -c "Session\\\Interface" "$CONFIG_FILE") == 0 ]]; then
  # if interface doenst exist in config, insert one
  sed -i "/\[BitTorrent\]/a Session\\\Interface=wg0" "$CONFIG_FILE"
else
  # replace interface
  sed -i "/Session\\\Interface=.*/s/=.*/=wg0/" "$CONFIG_FILE"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID /app/qbittorrent-nox --profile=/config
