#!/usr/bin/with-contenv sh

LOG_FILE=/config/qBittorrent/data/logs/qbittorrent.log

# create initial log file
if [[ ! -f "$LOG_FILE" ]]; then
  install -dm755 -o $PUID -g $PGID \
    /config/qBittorrent \
    /config/qBittorrent/data \
    /config/qBittorrent/data/logs

  install -m600 -o $PUID -g $PGID /dev/null "$LOG_FILE"
fi

# listen for logs
exec tail -F -n0 "$LOG_FILE"
